//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CODA11
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/", ConfigurationName="CODA11.Concentrator")]
    public interface Concentrator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.meterandcontrol.rs/CODA11/GetUnitsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemMethodDescriptor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemAttributeDescriptor))]
        System.Threading.Tasks.Task<CODA11.GetUnitsListResponse> GetUnitsListAsync(CODA11.GetUnitsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.meterandcontrol.rs/CODA11/GetUnitData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemMethodDescriptor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemAttributeDescriptor))]
        System.Threading.Tasks.Task<CODA11.GetUnitDataResponse> GetUnitDataAsync(CODA11.GetUnitDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.meterandcontrol.rs/CODA11/CosemUnitDirectCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemMethodDescriptor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CosemAttributeDescriptor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CosemUnitDirectCommandResponses")]
        System.Threading.Tasks.Task<CODA11.CosemUnitDirectCommandResponseValues> CosemUnitDirectCommandAsync(CODA11.CosemUnitDirectCommandRequestParameters CosemUnitDirectCommandParameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitsListUnit
    {
        
        private UnitsListUnitUnitDetail[] unitDetailField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UnitsListUnitUnitDetail[] UnitDetail
        {
            get
            {
                return this.unitDetailField;
            }
            set
            {
                this.unitDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitsListUnitUnitDetail
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemUnitDirectCommandResponseValues
    {
        
        private CosemUnitDirectCommandResponseValuesResponse[] responseField;
        
        private string unitIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CosemUnitDirectCommandResponseValuesResponse[] Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitID
        {
            get
            {
                return this.unitIDField;
            }
            set
            {
                this.unitIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemUnitDirectCommandResponseValuesResponse
    {
        
        private byte dataAccessResultField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public byte DataAccessResult
        {
            get
            {
                return this.dataAccessResultField;
            }
            set
            {
                this.dataAccessResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CosemAction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemMethodDescriptor
    {
        
        private ushort classIDField;
        
        private string instanceIDField;
        
        private string methodIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort ClassID
        {
            get
            {
                return this.classIDField;
            }
            set
            {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InstanceID
        {
            get
            {
                return this.instanceIDField;
            }
            set
            {
                this.instanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string MethodID
        {
            get
            {
                return this.methodIDField;
            }
            set
            {
                this.methodIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemAction : CosemMethodDescriptor
    {
        
        private byte[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CosemSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CosemGetWithSelector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CosemGet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemAttributeDescriptor
    {
        
        private ushort classIDField;
        
        private string instanceIDField;
        
        private string attributeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ushort ClassID
        {
            get
            {
                return this.classIDField;
            }
            set
            {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string InstanceID
        {
            get
            {
                return this.instanceIDField;
            }
            set
            {
                this.instanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string AttributeID
        {
            get
            {
                return this.attributeIDField;
            }
            set
            {
                this.attributeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemSet : CosemAttributeDescriptor
    {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemGetWithSelector : CosemAttributeDescriptor
    {
        
        private sbyte accessSelectorField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sbyte AccessSelector
        {
            get
            {
                return this.accessSelectorField;
            }
            set
            {
                this.accessSelectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemGet : CosemAttributeDescriptor
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class CosemUnitDirectCommandRequestParameters
    {
        
        private CosemGet[] getField;
        
        private CosemGetWithSelector[] getWithSelectorField;
        
        private CosemSet[] setField;
        
        private CosemAction[] actionField;
        
        private string unitIDField;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private System.DateTime endTimeField;
        
        private bool endTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Get", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CosemGet[] Get
        {
            get
            {
                return this.getField;
            }
            set
            {
                this.getField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetWithSelector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CosemGetWithSelector[] GetWithSelector
        {
            get
            {
                return this.getWithSelectorField;
            }
            set
            {
                this.getWithSelectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Set", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CosemSet[] Set
        {
            get
            {
                return this.setField;
            }
            set
            {
                this.setField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public CosemAction[] Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnitID
        {
            get
            {
                return this.unitIDField;
            }
            set
            {
                this.unitIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified
        {
            get
            {
                return this.startTimeFieldSpecified;
            }
            set
            {
                this.startTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeSpecified
        {
            get
            {
                return this.endTimeFieldSpecified;
            }
            set
            {
                this.endTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class Fault
    {
        
        private int faultCodeField;
        
        private string faultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FaultCode
        {
            get
            {
                return this.faultCodeField;
            }
            set
            {
                this.faultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FaultMessage
        {
            get
            {
                return this.faultMessageField;
            }
            set
            {
                this.faultMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitsList", WrapperNamespace="http://www.meterandcontrol.rs/CODA11/", IsWrapped=true)]
    public partial class GetUnitsListRequest
    {
        
        public GetUnitsListRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitsListResponse", WrapperNamespace="http://www.meterandcontrol.rs/CODA11/", IsWrapped=true)]
    public partial class GetUnitsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("Unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CODA11.UnitsListUnit[] UnitsList;
        
        public GetUnitsListResponse()
        {
        }
        
        public GetUnitsListResponse(CODA11.UnitsListUnit[] UnitsList)
        {
            this.UnitsList = UnitsList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class GetUnitDataParametersUnit
    {
        
        private GetUnitDataParametersUnitRegister[] registerField;
        
        private GetUnitDataParametersUnitProfile[] profileField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Register", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetUnitDataParametersUnitRegister[] Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Profile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public GetUnitDataParametersUnitProfile[] Profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class GetUnitDataParametersUnitRegister
    {
        
        private string idField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private bool lastValueOnlyField;
        
        public GetUnitDataParametersUnitRegister()
        {
            this.idField = "";
            this.lastValueOnlyField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LastValueOnly
        {
            get
            {
                return this.lastValueOnlyField;
            }
            set
            {
                this.lastValueOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class GetUnitDataParametersUnitProfile
    {
        
        private GetUnitDataParametersUnitProfileRegister[] registerField;
        
        private string idField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        public GetUnitDataParametersUnitProfile()
        {
            this.idField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Register", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GetUnitDataParametersUnitProfileRegister[] Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class GetUnitDataParametersUnitProfileRegister
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitDataUnit
    {
        
        private UnitDataUnitRegister[] registerField;
        
        private UnitDataUnitProfile[] profileField;
        
        private Fault faultField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Register", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UnitDataUnitRegister[] Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Profile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UnitDataUnitProfile[] Profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Fault Fault
        {
            get
            {
                return this.faultField;
            }
            set
            {
                this.faultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitDataUnitRegister
    {
        
        private string idField;
        
        private System.DateTime dateTimeField;
        
        private string valueField;
        
        private string statusField;
        
        private string unitField;
        
        public UnitDataUnitRegister()
        {
            this.statusField = "0";
            this.unitField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitDataUnitProfile
    {
        
        private UnitDataUnitProfileRegister[] registerField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Register", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UnitDataUnitProfileRegister[] Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.meterandcontrol.rs/CODA11/")]
    public partial class UnitDataUnitProfileRegister
    {
        
        private string idField;
        
        private System.DateTime dateTimeField;
        
        private string valueField;
        
        private string statusField;
        
        private string unitField;
        
        public UnitDataUnitProfileRegister()
        {
            this.statusField = "0";
            this.unitField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitData", WrapperNamespace="http://www.meterandcontrol.rs/CODA11/", IsWrapped=true)]
    public partial class GetUnitDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("Unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CODA11.GetUnitDataParametersUnit[] GetUnitDataParameters;
        
        public GetUnitDataRequest()
        {
        }
        
        public GetUnitDataRequest(CODA11.GetUnitDataParametersUnit[] GetUnitDataParameters)
        {
            this.GetUnitDataParameters = GetUnitDataParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUnitDataResponse", WrapperNamespace="http://www.meterandcontrol.rs/CODA11/", IsWrapped=true)]
    public partial class GetUnitDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("Unit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CODA11.UnitDataUnit[] Units;
        
        public GetUnitDataResponse()
        {
        }
        
        public GetUnitDataResponse(CODA11.UnitDataUnit[] Units)
        {
            this.Units = Units;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ConcentratorChannel : CODA11.Concentrator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ConcentratorClient : System.ServiceModel.ClientBase<CODA11.Concentrator>, CODA11.Concentrator
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConcentratorClient() : 
                base(ConcentratorClient.GetDefaultBinding(), ConcentratorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ConcentratorPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConcentratorClient(EndpointConfiguration endpointConfiguration) : 
                base(ConcentratorClient.GetBindingForEndpoint(endpointConfiguration), ConcentratorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConcentratorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConcentratorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConcentratorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConcentratorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConcentratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CODA11.GetUnitsListResponse> CODA11.Concentrator.GetUnitsListAsync(CODA11.GetUnitsListRequest request)
        {
            return base.Channel.GetUnitsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CODA11.GetUnitsListResponse> GetUnitsListAsync()
        {
            CODA11.GetUnitsListRequest inValue = new CODA11.GetUnitsListRequest();
            return ((CODA11.Concentrator)(this)).GetUnitsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CODA11.GetUnitDataResponse> CODA11.Concentrator.GetUnitDataAsync(CODA11.GetUnitDataRequest request)
        {
            return base.Channel.GetUnitDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CODA11.GetUnitDataResponse> GetUnitDataAsync(CODA11.GetUnitDataParametersUnit[] GetUnitDataParameters)
        {
            CODA11.GetUnitDataRequest inValue = new CODA11.GetUnitDataRequest();
            inValue.GetUnitDataParameters = GetUnitDataParameters;
            return ((CODA11.Concentrator)(this)).GetUnitDataAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<CODA11.CosemUnitDirectCommandResponseValues> CosemUnitDirectCommandAsync(CODA11.CosemUnitDirectCommandRequestParameters CosemUnitDirectCommandParameters)
        {
            return base.Channel.CosemUnitDirectCommandAsync(CosemUnitDirectCommandParameters);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConcentratorPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConcentratorPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.47/concentrator/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConcentratorClient.GetBindingForEndpoint(EndpointConfiguration.ConcentratorPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConcentratorClient.GetEndpointAddress(EndpointConfiguration.ConcentratorPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ConcentratorPort,
        }
    }
}
